# テスト実行用
apiVersion: v1
kind: Pod
metadata:
  name: webuitest
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: webuitest
      image: akishitara/cronjob-monitor
      command: ["webui"]
